on:
  push:
    branches: [ main ]
name: Send to production
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      
    - name: Manage API Key
      env: 
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
